name: qiscus_chat_sample
description: Qiscus Chat SDK Sample Project
version: 1.0.3+alpha1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^6.0.16
  timeago: ^2.0.26
  provider: ^4.1.3
  async:
  fluttertoast: ^4.0.1
  file_picker: ^1.10.0
  freezed_annotation:
  fluro: ^1.6.3
  date_format: ^1.0.8
  cuid: ^0.1.2
  flutter_bloc:
  qiscus_chat_sdk: ^1.0.4
  rxdart:
  grouped_list: ^3.2.3
  cupertino_icons: ^0.1.3

# useful for local development
dependency_overrides:
  qiscus_chat_sdk:
    path: ../chat-core

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/wallpaper/
